### PR TITLE
Add Python 3 support

### LINKED ISSUE #4: Python 3 support
Nodebook currently only supports python 2, but python 3 support should be included for the next major release.

### PR DESCRIPTION
**Pull request by jni**
Hi @kzielnicki! Thanks for nodebook, it's a great idea!

I think this should cover Python 3 support, but the installation of the notebook extension isn't working on IPython 6.x. Probably something needs to change in the install procedure that I haven't figured out yet.

Fixes #4.

### CODE REVIEW

**Comment by kzielnicki** [comment]
Thanks for the PR @jni! The way the extension was previously installed was rather hacky, so this is a good opportunity to change that. The issue is the javascript component of the extension. The current setup copies the javascript directly to the jupyter extensions directory (outside the package wheel) because I didn't figure any other good way to seamlessly install it programmatically, but this workaround was never really ideal (and indeed the current hack seems to not work at all in python 3), so I'll work on a different approach.

**Comment by jni** [comment]
@kzielnicki great, thanks! @carreau pointed me to this page for the latest docs on installing Jupyter extensions:

http://jupyter-notebook.readthedocs.io/en/stable/extending/frontend_extensions.html?highlight=extensions#installing-and-enabling-extensions

**Comment by Carreau** [comment]
I can try to review and give extra comments (this week will tough though). The best would be to copy / get inspiration from [jupyterlab](https://github.com/jupyterlab/jupyterlab) as they are just an extension of the notebook server. I would also have a look at the fantastic work [the Jupyter_Contrib](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) folks are doing as they have an extension to install/uninstall other extensions.

**Comment by kzielnicki** [comment]
Thanks @Carreau and @jni! I had originally hoped to avoid having a two-step installation process, but it looks like this is going to be unavoidable with pip. I'm merging this PR to a `py3` branch and taking a stab at updating the install from there.

**Pull request merged**
